services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'

    environment:
      DB_POSTGRES_HOST: postgres
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: proxy
      DB_POSTGRES_PASSWORD__FILE: /run/secrets/db_password
      DB_POSTGRES_NAME: proxy
      DISABLE_IPV6: true
      PUID: 1000
      PGID: 1000


    healthcheck:
      test: [ "CMD", "/usr/bin/check-health" ]
      interval: 10s
      timeout: 3s

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

    depends_on:
      - postgres

    secrets:
      - db_password

  postgres:
    image: postgres:latest

    environment:
      POSTGRES_USER: proxy
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: proxy
      USER: '1000:1000'

    volumes:
      - ./postgres:/var/lib/postgresql/data

    secrets:
      - db_password

secrets:
  db_password:
    file: ./secrets/db_password